security:
  # Configuration des hashers de mot de passe
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  # Configuration des providers
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  # Configuration des firewalls
  firewalls:
    main:
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Security\AppCustomAuthenticator

      # Permettre la déconnexion
      logout:
        path: app_logout
        target: /login

      # Activer la fonctionnalité "Remember me"
      remember_me:
        secret: "%kernel.secret%"
        lifetime: 604800 # 1 semaine en secondes
        path: /
        always_remember_me: false

  # Contrôle des accès
  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/profile, roles: ROLE_USER }
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/, roles: PUBLIC_ACCESS }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
